version: '3.8'
services:
  app:
    container_name: hr_app
    restart: always
    env_file: .env
    build: .
    environment:
      VIRTUAL_HOST: hr.esgi.dev
      VIRTUAL_PORT: 5005
      NODE_ENV: "development"
      WAIT_HOSTS: "db:${DB_PORT}"
    ports:
      - "${APP_PORT}:5005"
    expose:
      - 5005
    volumes:
      - ./secrets:/root/secrets:ro
      - .:/app
    networks:
      - db_network
      - web_network
    depends_on:
      - db
  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx-proxy/conf.d/my_proxy.conf:/etc/nginx/conf.d/my_proxy.conf:ro
      - ./secrets/certs:/etc/nginx/certs
      - ./config/nginx-proxy/vhost.d:/etc/nginx/vhost.d
      - ./config/nginx-proxy/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    restart: always
    # environment:
    #   - HTTPS_METHOD=nohttps
    expose:
      - "80"
      - "443"
    depends_on:
      - app
    networks:
      - web_network
  db:
    container_name: db
    restart: always
    image: "bitnami/postgresql:latest"
    env_file:
      - .env
    environment:
      - POSTGRESQL_DATABASE=${DB_NAME}
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_PORT_NUMBER=${DB_PORT}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    expose:
      - "${DB_PORT}"
    volumes:
      - postgresql_data:/bitnami/postgresql
    networks:
      - db_network
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
volumes:
  postgresql_data: